GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/652fa430a55fccc0d392c150

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name":"Harsh Garg",
  "number": "7867080884"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name":"",
  "number": "7867080884"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name":"Harsh Garg",
  "number": ""
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name":"Dan Abramov",
  "number": "7867080884"
}